//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WannaTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int group_id { get; set; }
        public string group_name { get; set; }
    }
}
