//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WannaTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int request_id { get; set; }
        public int request_item_id { get; set; }
        public int request_number { get; set; }
        public int request_price { get; set; }
        public int request_seller_id { get; set; }
        public bool request_is_on_sale { get; set; }
        public Nullable<int> request_buyer_id { get; set; }
        public Nullable<bool> request_is_seller_confirmed { get; set; }
        public Nullable<bool> request_is_buyer_confirmed { get; set; }
        public string request_status { get; set; }
        public Nullable<System.DateTime> request_creation_date { get; set; }
        public Nullable<System.DateTime> request_accept_date { get; set; }
    }
}
